add wait for lb step to prevent flakes due to apiserver not being ready.
Signed-off-by: Tom Hadlaw <tom.hadlaw@isovalent.com>

diff --git a/.github/workflows/conformance-pr.yml b/.github/workflows/conformance-pr.yml
--- a/.github/workflows/conformance-pr.yml
+++ b/.github/workflows/conformance-pr.yml
@@ -66,6 +66,12 @@ jobs:
       - name: Install Cilium
         run: |
           cd test/conformance
+          # Wait until the apiserver LB is ready
+          timeout 120 bash -c "until curl http://$(terraform output -raw elb_dns_name):443 -k -m 3; do sleep 1 && echo 'waiting for apiserver'; done"
+          if [ $? -ne 0 ]; then
+            echo "API Server LB failed to become available."
+            exit 1
+          fi
           export $(make print-kubeconfig)
           kubectl create -n kube-system secret generic cilium-ipsec-keys \
             --from-literal=keys="3 rfc4106(gcm(aes)) $(echo $(dd if=/dev/urandom count=20 bs=1 2> /dev/null | xxd -p -c 64)) 128"
